### ISSUE TITLE
A song of ice and fire api copywriting

### ISSUE THREAD

**Issue by benhoor** [got-show/general#10]
Hello,
I'm a new iOS app developer.
I'd like to create my own app using this api and upload it to the store.
Do I have to get a permission in order to do it?

Thanks in advance.

**Comment by sacdallago** [comment]
Hi @benhoor ,

this is very exciting! :) The data that you can access through the [API](http://api.got.show) is open, it would be nice though if you could reference [AWOIAF](http://awoiaf.westeros.org/index.php/Main_Page) and us in the about page (or similar).

Wish you much success! And send us a link to the app!

**Comment by benhoor** [comment]
This is awsome. :)
Thanks for your redponse.
I will reference you guys for sure.

Efi


בתאריך 25 ביוני 2017 8:39 אחה״צ,‏ "Christian Dallago" <
notifications@github.com> כתב:

Hi @benhoor <https://github.com/benhoor> ,

this is very exciting! :) The data that you can access through the API
<http://api.got.show> is open, it would be nice though if you could
reference AWOIAF <http://awoiaf.westeros.org/index.php/Main_Page> and us in
the about page (or similar).

Wish you much success! And send us a link to the app!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/got-show/general/issues/10#issuecomment-310916641>, or mute
the thread

**Comment by benhoor** [comment]
Hi Christian,

I have a question - I see in the "got" API that it's possible to add
character's plod values/sentiments and so on.
Did you intend to let anyone add this kind of info?

Let me explain: my idea is to create an app that shows Game of thrones info
(by user request).
I wonder if it makes sense to let the app users add/update the info in your
API.

Efi


On Sun, Jun 25, 2017 at 8:39 PM, Christian Dallago <notifications@github.com

**Comment by sacdallago** [comment]
@benhoor the short answer is: no.

We required this feature because the project was part of a class and we wanted the students to implement a CRUD stack mapping between database and web service. We don't have the infrastructure and people to really manage user access (at least CUD) on large scale, so the api online should be viewed as a read-only resource.

You can deploy an own instance of the API (and recreate the entire database from scratch) by running the steps in the readme [here](https://github.com/Rostlab/JS16_ProjectA) if you require it :)

Hope this helps!

**Comment by benhoor** [comment]
It helps, thanks again. :)

Efi

On Sun, Jul 2, 2017 at 10:05 PM, Christian Dallago <notifications@github.com

**Comment by benhoor** [comment]
Hi Christian,

I'm showing in my app the PLOD of the characters.
I see there are two algorithms of prediction called "gotplod" and "gotarffplod"
(maybe there are more and I missed it).
Can I read somewhere about these algorithms?
For example, I see that the former algorithm predicts that Jon snow's
chance to die is 11.6 (in %, I guess) while the latter shows 0.998.
Can you please clarify it for me?

Efi

**Comment by benhoor** [comment]
By the way - is there a legend for the plod values? Like if plod is below
X, then "the character is not likely to die", for example?
And another thing - if you guys want me to show specific info from your api
or any other idea, please let me know.

Efi

**Comment by benhoor** [comment]
Christian, I found your website with the algorithm description.

Tx.

Efi
